export const ADD_STAFF = "ADD_STAFF";

export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const STAFFS_RENDER = "STAFFS_RENDER";

export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";
export const DEPARTMENTS_RENDER = "DEPARTMENTS_RENDER";

export const STAFFSALARY_LOADING = "STAFFSALARY_LOADING";
export const STAFFSALARY_FAILED = "STAFFSALARY_FAILED";
export const STAFFSALARY_RENDER = "STAFFSALARY_RENDER";
